### PR TITLE
Add option for ignoring different types of quotes (fixes #916)

### LINKED ISSUE #916: NoSuperfluousConcatenationFixer replaces double quotes w single quotes
On a code base I work on, I have this line:

`printf('"%s";"%s";"%s"'."\r\n", ...$line);`

When I enable `NoSuperfluousConcatenationFixer`, this is the resulting code:

`printf("\"%s\";\"%s\";\"%s\"\r\n", ...$line);`

So the fixer concatenated the strings, but as a side effect introduced ugly escaping due to the double quotes now being used. I can work around this in my codebase, but it would be even better to have a setting for the fixer which controls if concatenations are retained if the type of quotes would have to be changed. In this case, such a setting would leave the code as-is.

(Apart from that: great tool.)

### PR DESCRIPTION
**Pull request by BlueM**
As described in https://github.com/kubawerlos/php-cs-fixer-custom-fixers/issues/916, a concatenation of single-quoted and double-quoted strings can be intentional to reduce quote escaping in the code.

This PR introduces a setting `keep_concatenation_for_different_quotes` which allows keeping such concatenations.

### CODE REVIEW

**Comment by kubawerlos** [comment]
@BlueM this option addition is a good idea, can you update PR?

**Comment by kubawerlos** [comment]
I have no idea why those few lines are reported, they look totally random.

It is intentional that dev tools run only on the latest stable PHP version, they are not part of the library's distribution. The library itself works on PHP 7.4+ (as proved by tests).

**Comment by kubawerlos** [comment]
Thank you @BlueM, I will fix the issues and release the feature.

**Comment by BlueM** [comment]
@kubawerlos: cool, thanks. By the way, while taking at the code yesterday I spotted a typo in my PR: in `NoSuperfluousConcatenationFixerTest.php`, line 189: “concatendated”.

**Comment by kubawerlos** [comment]
> @kubawerlos: cool, thanks. By the way, while taking at the code yesterday I spotted a typo in my PR: in `NoSuperfluousConcatenationFixerTest.php`, line 189: “concatendated”.

I've "spotted" it too, not in GitHub, but in PhpStorm.

**Pull request merged**
